GET http://localhost:8080
Accept: application/json

###

GET http://localhost:8080/recipes
Accept: application/json

###

POST http://localhost:8080/recipes/
Accept: application/json

{
    "name": "H and C 2",
    "ingredients": [
        {
            "name": "bread"
        },
        {
            "name": "ham"
        },
        {
            "name": "cheese"
        }
    ]
}

###

GET http://localhost:8080/recipes/
Accept: application/json